### ISSUE TITLE
100% CPU load after overload and lot of UnconfirmedWarning

### ISSUE THREAD

**Issue by DePizzottri** [DePizzottri/VKCrawler#40]
[ERROR] [09/14/2015 13:49:35.704] [kamon-akka.actor.default-dispatcher-30] [akka://kamon/user/kamon-system-metrics/sigar-metrics-recorder] Histogram recorded value cannot be negative.
java.lang.ArrayIndexOutOfBoundsException: Histogram recorded value cannot be negative.
    at org.HdrHistogram.AbstractHistogram.countsArrayIndex(AbstractHistogram.java:2024)
    at org.HdrHistogram.AbstractHistogram.recordSingleValue(AbstractHistogram.java:420)
    at org.HdrHistogram.AbstractHistogram.recordValue(AbstractHistogram.java:339)
    at kamon.metric.instrument.HdrHistogram.record(Histogram.scala:115)
    at kamon.system.sigar.ProcessCpuMetrics.update(ProcessCpuMetrics.scala:68)
    at kamon.system.sigar.SigarMetricsUpdater.updateMetrics(SigarMetricsUpdater.scala:49)
    at kamon.system.sigar.SigarMetricsUpdater$$anonfun$receive$1.applyOrElse(SigarMetricsUpdater.scala:44)
    at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
    at kamon.system.sigar.SigarMetricsUpdater.aroundReceive(SigarMetricsUpdater.scala:29)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
    at akka.actor.ActorCell.invoke_aroundBody0(ActorCell.scala:487)
    at akka.actor.ActorCell$AjcClosure1.run(ActorCell.scala:1)
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
    at akka.kamon.instrumentation.ActorCellInstrumentation$$anonfun$aroundBehaviourInvoke$1.apply(ActorCellInstrumentation.scala:63)
    at kamon.trace.Tracer$.withContext(TracerModule.scala:53)
    at akka.kamon.instrumentation.ActorCellInstrumentation.aroundBehaviourInvoke(ActorCellInstrumentation.scala:62)
    at akka.actor.ActorCell.invoke(ActorCell.scala:483)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
    at akka.dispatch.Mailbox.run(Mailbox.scala:220)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

**Comment by DePizzottri** [comment]
Problem appears without overload.
Seems to be bug in kamon
https://github.com/kamon-io/Kamon/issues/232
